// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AdminBearerAuthScopes adminBearerAuthContextKey = "adminBearerAuth.Scopes"
	SignatureAuthScopes   signatureAuthContextKey   = "signatureAuth.Scopes"
)

// Defines values for AdminActivityTone.
const (
	AdminActivityToneDanger  AdminActivityTone = "danger"
	AdminActivityToneInfo    AdminActivityTone = "info"
	AdminActivityToneSuccess AdminActivityTone = "success"
	AdminActivityToneWarning AdminActivityTone = "warning"
)

// Valid indicates whether the value is a known member of the AdminActivityTone enum.
func (e AdminActivityTone) Valid() bool {
	switch e {
	case AdminActivityToneDanger:
		return true
	case AdminActivityToneInfo:
		return true
	case AdminActivityToneSuccess:
		return true
	case AdminActivityToneWarning:
		return true
	default:
		return false
	}
}

// Defines values for AdminDashboardResponseSummarySmsStatus.
const (
	AdminDashboardResponseSummarySmsStatusConnected AdminDashboardResponseSummarySmsStatus = "connected"
	AdminDashboardResponseSummarySmsStatusStale     AdminDashboardResponseSummarySmsStatus = "stale"
)

// Valid indicates whether the value is a known member of the AdminDashboardResponseSummarySmsStatus enum.
func (e AdminDashboardResponseSummarySmsStatus) Valid() bool {
	switch e {
	case AdminDashboardResponseSummarySmsStatusConnected:
		return true
	case AdminDashboardResponseSummarySmsStatusStale:
		return true
	default:
		return false
	}
}

// Defines values for AdminEmailAccountStatus.
const (
	AdminEmailAccountStatusHealthy AdminEmailAccountStatus = "healthy"
	AdminEmailAccountStatusOffline AdminEmailAccountStatus = "offline"
	AdminEmailAccountStatusWarning AdminEmailAccountStatus = "warning"
)

// Valid indicates whether the value is a known member of the AdminEmailAccountStatus enum.
func (e AdminEmailAccountStatus) Valid() bool {
	switch e {
	case AdminEmailAccountStatusHealthy:
		return true
	case AdminEmailAccountStatusOffline:
		return true
	case AdminEmailAccountStatusWarning:
		return true
	default:
		return false
	}
}

// Defines values for AdminMessageStatus.
const (
	Accepted AdminMessageStatus = "accepted"
	Queued   AdminMessageStatus = "queued"
)

// Valid indicates whether the value is a known member of the AdminMessageStatus enum.
func (e AdminMessageStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Queued:
		return true
	default:
		return false
	}
}

// Defines values for AdminMessageChannel.
const (
	AdminMessageChannelEmail AdminMessageChannel = "email"
	AdminMessageChannelSms   AdminMessageChannel = "sms"
)

// Valid indicates whether the value is a known member of the AdminMessageChannel enum.
func (e AdminMessageChannel) Valid() bool {
	switch e {
	case AdminMessageChannelEmail:
		return true
	case AdminMessageChannelSms:
		return true
	default:
		return false
	}
}

// Defines values for AdminMessageContentMode.
const (
	Html     AdminMessageContentMode = "html"
	Plain    AdminMessageContentMode = "plain"
	Template AdminMessageContentMode = "template"
)

// Valid indicates whether the value is a known member of the AdminMessageContentMode enum.
func (e AdminMessageContentMode) Valid() bool {
	switch e {
	case Html:
		return true
	case Plain:
		return true
	case Template:
		return true
	default:
		return false
	}
}

// Defines values for AdminServiceScope.
const (
	AdminServiceScopeAll   AdminServiceScope = "all"
	AdminServiceScopeEmail AdminServiceScope = "email"
	AdminServiceScopeSms   AdminServiceScope = "sms"
)

// Valid indicates whether the value is a known member of the AdminServiceScope enum.
func (e AdminServiceScope) Valid() bool {
	switch e {
	case AdminServiceScopeAll:
		return true
	case AdminServiceScopeEmail:
		return true
	case AdminServiceScopeSms:
		return true
	default:
		return false
	}
}

// Defines values for AdminServiceStatus.
const (
	Active AdminServiceStatus = "active"
	Paused AdminServiceStatus = "paused"
)

// Valid indicates whether the value is a known member of the AdminServiceStatus enum.
func (e AdminServiceStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Paused:
		return true
	default:
		return false
	}
}

// Defines values for AdminSmsCredentialsStatus.
const (
	AdminSmsCredentialsStatusConnected AdminSmsCredentialsStatus = "connected"
	AdminSmsCredentialsStatusStale     AdminSmsCredentialsStatus = "stale"
)

// Valid indicates whether the value is a known member of the AdminSmsCredentialsStatus enum.
func (e AdminSmsCredentialsStatus) Valid() bool {
	switch e {
	case AdminSmsCredentialsStatusConnected:
		return true
	case AdminSmsCredentialsStatusStale:
		return true
	default:
		return false
	}
}

// AdminActivity defines model for AdminActivity.
type AdminActivity struct {
	CreatedAt time.Time         `json:"createdAt"`
	Detail    string            `json:"detail"`
	Id        string            `json:"id"`
	Title     string            `json:"title"`
	Tone      AdminActivityTone `json:"tone"`
}

// AdminActivityTone defines model for AdminActivityTone.
type AdminActivityTone string

// AdminDashboardResponse defines model for AdminDashboardResponse.
type AdminDashboardResponse struct {
	RecentActivity []AdminActivity `json:"recentActivity"`
	RecentMessages []AdminMessage  `json:"recentMessages"`
	Success        bool            `json:"success"`
	Summary        struct {
		ActiveServices      int                                    `json:"activeServices"`
		DefaultEmailAccount *string                                `json:"defaultEmailAccount"`
		EmailAccounts       int                                    `json:"emailAccounts"`
		QueuedMessages      int                                    `json:"queuedMessages"`
		Services            int                                    `json:"services"`
		SmsStatus           AdminDashboardResponseSummarySmsStatus `json:"smsStatus"`
	} `json:"summary"`
}

// AdminDashboardResponseSummarySmsStatus defines model for AdminDashboardResponse.Summary.SmsStatus.
type AdminDashboardResponseSummarySmsStatus string

// AdminEmailAccount defines model for AdminEmailAccount.
type AdminEmailAccount struct {
	Address      openapi_types.Email     `json:"address"`
	DisplayName  *string                 `json:"displayName,omitempty"`
	Id           string                  `json:"id"`
	IsDefault    *bool                   `json:"isDefault,omitempty"`
	LastTestedAt *time.Time              `json:"lastTestedAt,omitempty"`
	Smtp         AdminEmailSmtpConfig    `json:"smtp"`
	Status       AdminEmailAccountStatus `json:"status"`
}

// AdminEmailAccountCreateRequest defines model for AdminEmailAccountCreateRequest.
type AdminEmailAccountCreateRequest struct {
	Address     openapi_types.Email  `json:"address"`
	DisplayName *string              `json:"displayName,omitempty"`
	Id          string               `json:"id"`
	IsDefault   *bool                `json:"isDefault,omitempty"`
	Smtp        AdminEmailSmtpConfig `json:"smtp"`
}

// AdminEmailAccountListResponse defines model for AdminEmailAccountListResponse.
type AdminEmailAccountListResponse struct {
	EmailAccounts []AdminEmailAccount `json:"emailAccounts"`
	Success       bool                `json:"success"`
}

// AdminEmailAccountResponse defines model for AdminEmailAccountResponse.
type AdminEmailAccountResponse struct {
	EmailAccount AdminEmailAccount `json:"emailAccount"`
	Success      bool              `json:"success"`
}

// AdminEmailAccountStatus defines model for AdminEmailAccountStatus.
type AdminEmailAccountStatus string

// AdminEmailAccountTestResponse defines model for AdminEmailAccountTestResponse.
type AdminEmailAccountTestResponse struct {
	EmailAccount AdminEmailAccount `json:"emailAccount"`
	Message      *string           `json:"message,omitempty"`
	Success      bool              `json:"success"`
	TestedAt     time.Time         `json:"testedAt"`
}

// AdminEmailAccountUpdateRequest defines model for AdminEmailAccountUpdateRequest.
type AdminEmailAccountUpdateRequest struct {
	Address     *openapi_types.Email  `json:"address,omitempty"`
	DisplayName *string               `json:"displayName,omitempty"`
	IsDefault   *bool                 `json:"isDefault,omitempty"`
	Smtp        *AdminEmailSmtpConfig `json:"smtp,omitempty"`
}

// AdminEmailSmtpConfig defines model for AdminEmailSmtpConfig.
type AdminEmailSmtpConfig struct {
	Host     string `json:"host"`
	Password string `json:"password"`
	Port     int    `json:"port"`
	Username string `json:"username"`
}

// AdminLoginRequest defines model for AdminLoginRequest.
type AdminLoginRequest struct {
	Password string `json:"password"`
	TotpCode string `json:"totpCode"`
	Username string `json:"username"`
}

// AdminLoginResponse defines model for AdminLoginResponse.
type AdminLoginResponse struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Success   bool      `json:"success"`
	Token     string    `json:"token"`
	User      AdminUser `json:"user"`
}

// AdminMeResponse defines model for AdminMeResponse.
type AdminMeResponse struct {
	Success bool      `json:"success"`
	User    AdminUser `json:"user"`
}

// AdminMessage defines model for AdminMessage.
type AdminMessage struct {
	Body         *string                 `json:"body,omitempty"`
	Channel      AdminMessageChannel     `json:"channel"`
	ContentMode  AdminMessageContentMode `json:"contentMode"`
	CreatedAt    time.Time               `json:"createdAt"`
	Id           string                  `json:"id"`
	Recipients   []string                `json:"recipients"`
	Sender       string                  `json:"sender"`
	ServiceId    string                  `json:"serviceId"`
	Status       AdminMessageStatus      `json:"status"`
	Subject      *string                 `json:"subject,omitempty"`
	TemplateName *string                 `json:"templateName,omitempty"`
}

// AdminMessageStatus defines model for AdminMessage.Status.
type AdminMessageStatus string

// AdminMessageChannel defines model for AdminMessageChannel.
type AdminMessageChannel string

// AdminMessageContentMode defines model for AdminMessageContentMode.
type AdminMessageContentMode string

// AdminMessageListResponse defines model for AdminMessageListResponse.
type AdminMessageListResponse struct {
	Messages []AdminMessage `json:"messages"`
	Success  bool           `json:"success"`
}

// AdminMessagePreviewResponse defines model for AdminMessagePreviewResponse.
type AdminMessagePreviewResponse struct {
	Preview struct {
		Rendered string              `json:"rendered"`
		Request  AdminMessageRequest `json:"request"`
		Warnings *[]string           `json:"warnings,omitempty"`
	} `json:"preview"`
	Success bool `json:"success"`
}

// AdminMessageRequest defines model for AdminMessageRequest.
type AdminMessageRequest struct {
	Body        *string                 `json:"body,omitempty"`
	Channel     AdminMessageChannel     `json:"channel"`
	ContentMode AdminMessageContentMode `json:"contentMode"`
	From        *openapi_types.Email    `json:"from,omitempty"`
	Recipients  []string                `json:"recipients"`
	SenderName  *string                 `json:"senderName,omitempty"`
	ServiceId   string                  `json:"serviceId"`
	Subject     *string                 `json:"subject,omitempty"`
	Template    *AdminMessageTemplate   `json:"template,omitempty"`
}

// AdminMessageSubmitResponse defines model for AdminMessageSubmitResponse.
type AdminMessageSubmitResponse struct {
	Message       string       `json:"message"`
	QueuedMessage AdminMessage `json:"queuedMessage"`
	Success       bool         `json:"success"`
}

// AdminMessageTemplate defines model for AdminMessageTemplate.
type AdminMessageTemplate struct {
	Data map[string]interface{} `json:"data"`
	Name string                 `json:"name"`
}

// AdminService defines model for AdminService.
type AdminService struct {
	CreatedAt    *time.Time         `json:"createdAt,omitempty"`
	Id           string             `json:"id"`
	LastRerollAt *time.Time         `json:"lastRerollAt,omitempty"`
	Name         string             `json:"name"`
	Notes        *string            `json:"notes,omitempty"`
	Owner        *string            `json:"owner,omitempty"`
	PublicKey    string             `json:"publicKey"`
	Scope        AdminServiceScope  `json:"scope"`
	Status       AdminServiceStatus `json:"status"`
}

// AdminServiceCreateRequest defines model for AdminServiceCreateRequest.
type AdminServiceCreateRequest struct {
	Id        string             `json:"id"`
	Name      string             `json:"name"`
	Notes     *string            `json:"notes,omitempty"`
	Owner     *string            `json:"owner,omitempty"`
	PublicKey string             `json:"publicKey"`
	Scope     AdminServiceScope  `json:"scope"`
	Status    AdminServiceStatus `json:"status"`
}

// AdminServiceListResponse defines model for AdminServiceListResponse.
type AdminServiceListResponse struct {
	Services []AdminService `json:"services"`
	Success  bool           `json:"success"`
}

// AdminServiceRerollResponse defines model for AdminServiceRerollResponse.
type AdminServiceRerollResponse struct {
	// PrivateKey One-time secret returned when a keypair is rerolled.
	PrivateKey string       `json:"privateKey"`
	Service    AdminService `json:"service"`
	Success    bool         `json:"success"`
}

// AdminServiceResponse defines model for AdminServiceResponse.
type AdminServiceResponse struct {
	Service AdminService `json:"service"`
	Success bool         `json:"success"`
}

// AdminServiceScope defines model for AdminServiceScope.
type AdminServiceScope string

// AdminServiceStatus defines model for AdminServiceStatus.
type AdminServiceStatus string

// AdminServiceUpdateRequest defines model for AdminServiceUpdateRequest.
type AdminServiceUpdateRequest struct {
	Name      *string             `json:"name,omitempty"`
	Notes     *string             `json:"notes,omitempty"`
	Owner     *string             `json:"owner,omitempty"`
	PublicKey *string             `json:"publicKey,omitempty"`
	Scope     *AdminServiceScope  `json:"scope,omitempty"`
	Status    *AdminServiceStatus `json:"status,omitempty"`
}

// AdminSmsCredentials defines model for AdminSmsCredentials.
type AdminSmsCredentials struct {
	LastSyncedAt  time.Time                 `json:"lastSyncedAt"`
	Password      string                    `json:"password"`
	RotationCount int                       `json:"rotationCount"`
	Status        AdminSmsCredentialsStatus `json:"status"`
	Username      string                    `json:"username"`
}

// AdminSmsCredentialsStatus defines model for AdminSmsCredentials.Status.
type AdminSmsCredentialsStatus string

// AdminSmsCredentialsResponse defines model for AdminSmsCredentialsResponse.
type AdminSmsCredentialsResponse struct {
	SmsCredentials AdminSmsCredentials `json:"smsCredentials"`
	Success        bool                `json:"success"`
}

// AdminSmsCredentialsRotateResponse defines model for AdminSmsCredentialsRotateResponse.
type AdminSmsCredentialsRotateResponse struct {
	SmsCredentials AdminSmsCredentials `json:"smsCredentials"`
	Success        bool                `json:"success"`
}

// AdminSmsCredentialsUpdateRequest defines model for AdminSmsCredentialsUpdateRequest.
type AdminSmsCredentialsUpdateRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// AdminUser defines model for AdminUser.
type AdminUser struct {
	CreatedAt   time.Time  `json:"createdAt"`
	Id          string     `json:"id"`
	LastLoginAt *time.Time `json:"lastLoginAt,omitempty"`
	UpdatedAt   time.Time  `json:"updatedAt"`
	Username    string     `json:"username"`
}

// AdminUserCreateRequest defines model for AdminUserCreateRequest.
type AdminUserCreateRequest struct {
	Username string `json:"username"`
}

// AdminUserCreateResponse defines model for AdminUserCreateResponse.
type AdminUserCreateResponse struct {
	Credentials AdminUserCredentials `json:"credentials"`
	Success     bool                 `json:"success"`
	User        AdminUser            `json:"user"`
}

// AdminUserCredentials defines model for AdminUserCredentials.
type AdminUserCredentials struct {
	Password        string `json:"password"`
	ProvisioningUri string `json:"provisioningUri"`
	TotpSecret      string `json:"totpSecret"`
}

// AdminUserListResponse defines model for AdminUserListResponse.
type AdminUserListResponse struct {
	Success bool        `json:"success"`
	Users   []AdminUser `json:"users"`
}

// EmailContact defines model for EmailContact.
type EmailContact struct {
	Address openapi_types.Email `json:"address"`
	Name    *string             `json:"name,omitempty"`
}

// EmailRequest defines model for EmailRequest.
type EmailRequest struct {
	Content *EmailRequest_Content `json:"content,omitempty"`
	From    EmailContact          `json:"from"`
	Subject string                `json:"subject"`

	// To A single recipient or an array of recipients.
	To EmailRequest_To `json:"to"`
}

// EmailRequestContent0 defines model for .
type EmailRequestContent0 struct {
	Body   string `json:"body"`
	IsHtml *bool  `json:"isHtml,omitempty"`
}

// EmailRequestContent1 defines model for .
type EmailRequestContent1 struct {
	Template struct {
		Data map[string]interface{} `json:"data"`
		Name string                 `json:"name"`
	} `json:"template"`
}

// EmailRequest_Content defines model for EmailRequest.Content.
type EmailRequest_Content struct {
	union json.RawMessage
}

// EmailRequestTo0 defines model for .
type EmailRequestTo0 = openapi_types.Email

// EmailRequestTo2 defines model for .
type EmailRequestTo2 = []EmailRequest_To_2_Item

// EmailRequestTo20 defines model for .
type EmailRequestTo20 = openapi_types.Email

// EmailRequest_To_2_Item defines model for EmailRequest.To.2.Item.
type EmailRequest_To_2_Item struct {
	union json.RawMessage
}

// EmailRequest_To A single recipient or an array of recipients.
type EmailRequest_To struct {
	union json.RawMessage
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    string    `json:"code"`
		Details *[]string `json:"details,omitempty"`
		Message string    `json:"message"`
	} `json:"error"`
	Success bool `json:"success"`
}

// SmsRecipient defines model for SmsRecipient.
type SmsRecipient struct {
	union json.RawMessage
}

// SmsRecipient0 Phone number in E.164 format.
type SmsRecipient0 = string

// SmsRecipient1 defines model for .
type SmsRecipient1 struct {
	// Country ISO 3166-1 alpha-2 country code.
	Country string `json:"country"`
	Phone   string `json:"phone"`
}

// SmsRequest defines model for SmsRequest.
type SmsRequest struct {
	Content    *SmsRequest_Content `json:"content,omitempty"`
	SenderName string              `json:"senderName"`

	// To A single recipient or an array of recipients.
	To SmsRequest_To `json:"to"`
}

// SmsRequestContent0 defines model for .
type SmsRequestContent0 struct {
	Body string `json:"body"`
}

// SmsRequestContent1 defines model for .
type SmsRequestContent1 struct {
	Template struct {
		Data map[string]interface{} `json:"data"`
		Name string                 `json:"name"`
	} `json:"template"`
}

// SmsRequest_Content defines model for SmsRequest.Content.
type SmsRequest_Content struct {
	union json.RawMessage
}

// SmsRequestTo1 defines model for .
type SmsRequestTo1 = []SmsRecipient

// SmsRequest_To A single recipient or an array of recipients.
type SmsRequest_To struct {
	union json.RawMessage
}

// SmsSuccessResponse defines model for SmsSuccessResponse.
type SmsSuccessResponse struct {
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message string                  `json:"message"`
	Meta    *struct {
		Cost     *float32 `json:"cost,omitempty"`
		Currency *string  `json:"currency,omitempty"`
	} `json:"meta,omitempty"`
	Success bool `json:"success"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message string                  `json:"message"`
	Success bool                    `json:"success"`
}

// ClientIdHeader defines model for ClientIdHeader.
type ClientIdHeader = string

// TimestampHeader defines model for TimestampHeader.
type TimestampHeader = time.Time

// adminBearerAuthContextKey is the context key for adminBearerAuth security scheme
type adminBearerAuthContextKey string

// signatureAuthContextKey is the context key for signatureAuth security scheme
type signatureAuthContextKey string

// GetAdminMessagesParams defines parameters for GetAdminMessages.
type GetAdminMessagesParams struct {
	Limit     *int                 `form:"limit,omitempty" json:"limit,omitempty"`
	Channel   *AdminMessageChannel `form:"channel,omitempty" json:"channel,omitempty"`
	ServiceId *string              `form:"serviceId,omitempty" json:"serviceId,omitempty"`
}

// PostV3EmailParams defines parameters for PostV3Email.
type PostV3EmailParams struct {
	// XClientId The unique ID assigned to your service.
	XClientId ClientIdHeader `json:"X-Client-Id"`

	// XTimestamp ISO 8601 timestamp. Requests older than 5 minutes will be rejected.
	XTimestamp TimestampHeader `json:"X-Timestamp"`
}

// PostV3SmsParams defines parameters for PostV3Sms.
type PostV3SmsParams struct {
	// XClientId The unique ID assigned to your service.
	XClientId ClientIdHeader `json:"X-Client-Id"`

	// XTimestamp ISO 8601 timestamp. Requests older than 5 minutes will be rejected.
	XTimestamp TimestampHeader `json:"X-Timestamp"`
}

// AdminLoginJSONRequestBody defines body for AdminLogin for application/json ContentType.
type AdminLoginJSONRequestBody = AdminLoginRequest

// CreateAdminEmailAccountJSONRequestBody defines body for CreateAdminEmailAccount for application/json ContentType.
type CreateAdminEmailAccountJSONRequestBody = AdminEmailAccountCreateRequest

// UpdateAdminEmailAccountJSONRequestBody defines body for UpdateAdminEmailAccount for application/json ContentType.
type UpdateAdminEmailAccountJSONRequestBody = AdminEmailAccountUpdateRequest

// CreateAdminMessageJSONRequestBody defines body for CreateAdminMessage for application/json ContentType.
type CreateAdminMessageJSONRequestBody = AdminMessageRequest

// PreviewAdminMessageJSONRequestBody defines body for PreviewAdminMessage for application/json ContentType.
type PreviewAdminMessageJSONRequestBody = AdminMessageRequest

// CreateAdminServiceJSONRequestBody defines body for CreateAdminService for application/json ContentType.
type CreateAdminServiceJSONRequestBody = AdminServiceCreateRequest

// UpdateAdminServiceJSONRequestBody defines body for UpdateAdminService for application/json ContentType.
type UpdateAdminServiceJSONRequestBody = AdminServiceUpdateRequest

// UpdateAdminSmsCredentialsJSONRequestBody defines body for UpdateAdminSmsCredentials for application/json ContentType.
type UpdateAdminSmsCredentialsJSONRequestBody = AdminSmsCredentialsUpdateRequest

// CreateAdminUserJSONRequestBody defines body for CreateAdminUser for application/json ContentType.
type CreateAdminUserJSONRequestBody = AdminUserCreateRequest

// PostV3EmailJSONRequestBody defines body for PostV3Email for application/json ContentType.
type PostV3EmailJSONRequestBody = EmailRequest

// PostV3SmsJSONRequestBody defines body for PostV3Sms for application/json ContentType.
type PostV3SmsJSONRequestBody = SmsRequest

// AsEmailRequestContent0 returns the union data inside the EmailRequest_Content as a EmailRequestContent0
func (t EmailRequest_Content) AsEmailRequestContent0() (EmailRequestContent0, error) {
	var body EmailRequestContent0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmailRequestContent0 overwrites any union data inside the EmailRequest_Content as the provided EmailRequestContent0
func (t *EmailRequest_Content) FromEmailRequestContent0(v EmailRequestContent0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmailRequestContent0 performs a merge with any union data inside the EmailRequest_Content, using the provided EmailRequestContent0
func (t *EmailRequest_Content) MergeEmailRequestContent0(v EmailRequestContent0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmailRequestContent1 returns the union data inside the EmailRequest_Content as a EmailRequestContent1
func (t EmailRequest_Content) AsEmailRequestContent1() (EmailRequestContent1, error) {
	var body EmailRequestContent1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmailRequestContent1 overwrites any union data inside the EmailRequest_Content as the provided EmailRequestContent1
func (t *EmailRequest_Content) FromEmailRequestContent1(v EmailRequestContent1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmailRequestContent1 performs a merge with any union data inside the EmailRequest_Content, using the provided EmailRequestContent1
func (t *EmailRequest_Content) MergeEmailRequestContent1(v EmailRequestContent1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmailRequest_Content) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EmailRequest_Content) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEmailRequestTo20 returns the union data inside the EmailRequest_To_2_Item as a EmailRequestTo20
func (t EmailRequest_To_2_Item) AsEmailRequestTo20() (EmailRequestTo20, error) {
	var body EmailRequestTo20
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmailRequestTo20 overwrites any union data inside the EmailRequest_To_2_Item as the provided EmailRequestTo20
func (t *EmailRequest_To_2_Item) FromEmailRequestTo20(v EmailRequestTo20) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmailRequestTo20 performs a merge with any union data inside the EmailRequest_To_2_Item, using the provided EmailRequestTo20
func (t *EmailRequest_To_2_Item) MergeEmailRequestTo20(v EmailRequestTo20) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmailContact returns the union data inside the EmailRequest_To_2_Item as a EmailContact
func (t EmailRequest_To_2_Item) AsEmailContact() (EmailContact, error) {
	var body EmailContact
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmailContact overwrites any union data inside the EmailRequest_To_2_Item as the provided EmailContact
func (t *EmailRequest_To_2_Item) FromEmailContact(v EmailContact) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmailContact performs a merge with any union data inside the EmailRequest_To_2_Item, using the provided EmailContact
func (t *EmailRequest_To_2_Item) MergeEmailContact(v EmailContact) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmailRequest_To_2_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EmailRequest_To_2_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEmailRequestTo0 returns the union data inside the EmailRequest_To as a EmailRequestTo0
func (t EmailRequest_To) AsEmailRequestTo0() (EmailRequestTo0, error) {
	var body EmailRequestTo0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmailRequestTo0 overwrites any union data inside the EmailRequest_To as the provided EmailRequestTo0
func (t *EmailRequest_To) FromEmailRequestTo0(v EmailRequestTo0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmailRequestTo0 performs a merge with any union data inside the EmailRequest_To, using the provided EmailRequestTo0
func (t *EmailRequest_To) MergeEmailRequestTo0(v EmailRequestTo0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmailContact returns the union data inside the EmailRequest_To as a EmailContact
func (t EmailRequest_To) AsEmailContact() (EmailContact, error) {
	var body EmailContact
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmailContact overwrites any union data inside the EmailRequest_To as the provided EmailContact
func (t *EmailRequest_To) FromEmailContact(v EmailContact) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmailContact performs a merge with any union data inside the EmailRequest_To, using the provided EmailContact
func (t *EmailRequest_To) MergeEmailContact(v EmailContact) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmailRequestTo2 returns the union data inside the EmailRequest_To as a EmailRequestTo2
func (t EmailRequest_To) AsEmailRequestTo2() (EmailRequestTo2, error) {
	var body EmailRequestTo2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmailRequestTo2 overwrites any union data inside the EmailRequest_To as the provided EmailRequestTo2
func (t *EmailRequest_To) FromEmailRequestTo2(v EmailRequestTo2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmailRequestTo2 performs a merge with any union data inside the EmailRequest_To, using the provided EmailRequestTo2
func (t *EmailRequest_To) MergeEmailRequestTo2(v EmailRequestTo2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmailRequest_To) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EmailRequest_To) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSmsRecipient0 returns the union data inside the SmsRecipient as a SmsRecipient0
func (t SmsRecipient) AsSmsRecipient0() (SmsRecipient0, error) {
	var body SmsRecipient0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSmsRecipient0 overwrites any union data inside the SmsRecipient as the provided SmsRecipient0
func (t *SmsRecipient) FromSmsRecipient0(v SmsRecipient0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSmsRecipient0 performs a merge with any union data inside the SmsRecipient, using the provided SmsRecipient0
func (t *SmsRecipient) MergeSmsRecipient0(v SmsRecipient0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSmsRecipient1 returns the union data inside the SmsRecipient as a SmsRecipient1
func (t SmsRecipient) AsSmsRecipient1() (SmsRecipient1, error) {
	var body SmsRecipient1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSmsRecipient1 overwrites any union data inside the SmsRecipient as the provided SmsRecipient1
func (t *SmsRecipient) FromSmsRecipient1(v SmsRecipient1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSmsRecipient1 performs a merge with any union data inside the SmsRecipient, using the provided SmsRecipient1
func (t *SmsRecipient) MergeSmsRecipient1(v SmsRecipient1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SmsRecipient) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SmsRecipient) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSmsRequestContent0 returns the union data inside the SmsRequest_Content as a SmsRequestContent0
func (t SmsRequest_Content) AsSmsRequestContent0() (SmsRequestContent0, error) {
	var body SmsRequestContent0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSmsRequestContent0 overwrites any union data inside the SmsRequest_Content as the provided SmsRequestContent0
func (t *SmsRequest_Content) FromSmsRequestContent0(v SmsRequestContent0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSmsRequestContent0 performs a merge with any union data inside the SmsRequest_Content, using the provided SmsRequestContent0
func (t *SmsRequest_Content) MergeSmsRequestContent0(v SmsRequestContent0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSmsRequestContent1 returns the union data inside the SmsRequest_Content as a SmsRequestContent1
func (t SmsRequest_Content) AsSmsRequestContent1() (SmsRequestContent1, error) {
	var body SmsRequestContent1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSmsRequestContent1 overwrites any union data inside the SmsRequest_Content as the provided SmsRequestContent1
func (t *SmsRequest_Content) FromSmsRequestContent1(v SmsRequestContent1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSmsRequestContent1 performs a merge with any union data inside the SmsRequest_Content, using the provided SmsRequestContent1
func (t *SmsRequest_Content) MergeSmsRequestContent1(v SmsRequestContent1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SmsRequest_Content) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SmsRequest_Content) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSmsRecipient returns the union data inside the SmsRequest_To as a SmsRecipient
func (t SmsRequest_To) AsSmsRecipient() (SmsRecipient, error) {
	var body SmsRecipient
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSmsRecipient overwrites any union data inside the SmsRequest_To as the provided SmsRecipient
func (t *SmsRequest_To) FromSmsRecipient(v SmsRecipient) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSmsRecipient performs a merge with any union data inside the SmsRequest_To, using the provided SmsRecipient
func (t *SmsRequest_To) MergeSmsRecipient(v SmsRecipient) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSmsRequestTo1 returns the union data inside the SmsRequest_To as a SmsRequestTo1
func (t SmsRequest_To) AsSmsRequestTo1() (SmsRequestTo1, error) {
	var body SmsRequestTo1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSmsRequestTo1 overwrites any union data inside the SmsRequest_To as the provided SmsRequestTo1
func (t *SmsRequest_To) FromSmsRequestTo1(v SmsRequestTo1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSmsRequestTo1 performs a merge with any union data inside the SmsRequest_To, using the provided SmsRequestTo1
func (t *SmsRequest_To) MergeSmsRequestTo1(v SmsRequestTo1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SmsRequest_To) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SmsRequest_To) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Service Health Check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Log in to the admin console
	// (POST /v3/admin/auth/login)
	AdminLogin(w http.ResponseWriter, r *http.Request)
	// Inspect the current admin session
	// (GET /v3/admin/auth/me)
	GetAdminAuthMe(w http.ResponseWriter, r *http.Request)
	// Admin dashboard summary
	// (GET /v3/admin/dashboard)
	GetV3AdminDashboard(w http.ResponseWriter, r *http.Request)
	// List SMTP accounts
	// (GET /v3/admin/email-accounts)
	GetAdminEmailAccounts(w http.ResponseWriter, r *http.Request)
	// Create an SMTP account
	// (POST /v3/admin/email-accounts)
	CreateAdminEmailAccount(w http.ResponseWriter, r *http.Request)
	// Delete an SMTP account
	// (DELETE /v3/admin/email-accounts/{accountId})
	DeleteAdminEmailAccount(w http.ResponseWriter, r *http.Request, accountId string)
	// Get an SMTP account
	// (GET /v3/admin/email-accounts/{accountId})
	GetAdminEmailAccount(w http.ResponseWriter, r *http.Request, accountId string)
	// Update an SMTP account
	// (PUT /v3/admin/email-accounts/{accountId})
	UpdateAdminEmailAccount(w http.ResponseWriter, r *http.Request, accountId string)
	// Test an SMTP account
	// (POST /v3/admin/email-accounts/{accountId}/test)
	TestAdminEmailAccount(w http.ResponseWriter, r *http.Request, accountId string)
	// List delivery messages
	// (GET /v3/admin/messages)
	GetAdminMessages(w http.ResponseWriter, r *http.Request, params GetAdminMessagesParams)
	// Queue a delivery message
	// (POST /v3/admin/messages)
	CreateAdminMessage(w http.ResponseWriter, r *http.Request)
	// Preview a delivery message
	// (POST /v3/admin/messages/preview)
	PreviewAdminMessage(w http.ResponseWriter, r *http.Request)
	// List services with API access
	// (GET /v3/admin/services)
	GetAdminServices(w http.ResponseWriter, r *http.Request)
	// Create a service identity
	// (POST /v3/admin/services)
	CreateAdminService(w http.ResponseWriter, r *http.Request)
	// Delete a service identity
	// (DELETE /v3/admin/services/{serviceId})
	DeleteAdminService(w http.ResponseWriter, r *http.Request, serviceId string)
	// Get a service identity
	// (GET /v3/admin/services/{serviceId})
	GetAdminService(w http.ResponseWriter, r *http.Request, serviceId string)
	// Update a service identity
	// (PUT /v3/admin/services/{serviceId})
	UpdateAdminService(w http.ResponseWriter, r *http.Request, serviceId string)
	// Reroll a service keypair
	// (POST /v3/admin/services/{serviceId}/reroll)
	RerollAdminService(w http.ResponseWriter, r *http.Request, serviceId string)
	// Get 46elks credentials
	// (GET /v3/admin/sms-credentials)
	GetAdminSmsCredentials(w http.ResponseWriter, r *http.Request)
	// Update 46elks credentials
	// (PUT /v3/admin/sms-credentials)
	UpdateAdminSmsCredentials(w http.ResponseWriter, r *http.Request)
	// Rotate 46elks credentials
	// (POST /v3/admin/sms-credentials/rotate)
	RotateAdminSmsCredentials(w http.ResponseWriter, r *http.Request)
	// List admin users
	// (GET /v3/admin/users)
	GetAdminUsers(w http.ResponseWriter, r *http.Request)
	// Create an admin user
	// (POST /v3/admin/users)
	CreateAdminUser(w http.ResponseWriter, r *http.Request)
	// Send an Email
	// (POST /v3/email)
	PostV3Email(w http.ResponseWriter, r *http.Request, params PostV3EmailParams)
	// Send an SMS
	// (POST /v3/sms)
	PostV3Sms(w http.ResponseWriter, r *http.Request, params PostV3SmsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Service Health Check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Log in to the admin console
// (POST /v3/admin/auth/login)
func (_ Unimplemented) AdminLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Inspect the current admin session
// (GET /v3/admin/auth/me)
func (_ Unimplemented) GetAdminAuthMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Admin dashboard summary
// (GET /v3/admin/dashboard)
func (_ Unimplemented) GetV3AdminDashboard(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List SMTP accounts
// (GET /v3/admin/email-accounts)
func (_ Unimplemented) GetAdminEmailAccounts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an SMTP account
// (POST /v3/admin/email-accounts)
func (_ Unimplemented) CreateAdminEmailAccount(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an SMTP account
// (DELETE /v3/admin/email-accounts/{accountId})
func (_ Unimplemented) DeleteAdminEmailAccount(w http.ResponseWriter, r *http.Request, accountId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get an SMTP account
// (GET /v3/admin/email-accounts/{accountId})
func (_ Unimplemented) GetAdminEmailAccount(w http.ResponseWriter, r *http.Request, accountId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an SMTP account
// (PUT /v3/admin/email-accounts/{accountId})
func (_ Unimplemented) UpdateAdminEmailAccount(w http.ResponseWriter, r *http.Request, accountId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Test an SMTP account
// (POST /v3/admin/email-accounts/{accountId}/test)
func (_ Unimplemented) TestAdminEmailAccount(w http.ResponseWriter, r *http.Request, accountId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List delivery messages
// (GET /v3/admin/messages)
func (_ Unimplemented) GetAdminMessages(w http.ResponseWriter, r *http.Request, params GetAdminMessagesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Queue a delivery message
// (POST /v3/admin/messages)
func (_ Unimplemented) CreateAdminMessage(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Preview a delivery message
// (POST /v3/admin/messages/preview)
func (_ Unimplemented) PreviewAdminMessage(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List services with API access
// (GET /v3/admin/services)
func (_ Unimplemented) GetAdminServices(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a service identity
// (POST /v3/admin/services)
func (_ Unimplemented) CreateAdminService(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a service identity
// (DELETE /v3/admin/services/{serviceId})
func (_ Unimplemented) DeleteAdminService(w http.ResponseWriter, r *http.Request, serviceId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a service identity
// (GET /v3/admin/services/{serviceId})
func (_ Unimplemented) GetAdminService(w http.ResponseWriter, r *http.Request, serviceId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a service identity
// (PUT /v3/admin/services/{serviceId})
func (_ Unimplemented) UpdateAdminService(w http.ResponseWriter, r *http.Request, serviceId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reroll a service keypair
// (POST /v3/admin/services/{serviceId}/reroll)
func (_ Unimplemented) RerollAdminService(w http.ResponseWriter, r *http.Request, serviceId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get 46elks credentials
// (GET /v3/admin/sms-credentials)
func (_ Unimplemented) GetAdminSmsCredentials(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update 46elks credentials
// (PUT /v3/admin/sms-credentials)
func (_ Unimplemented) UpdateAdminSmsCredentials(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rotate 46elks credentials
// (POST /v3/admin/sms-credentials/rotate)
func (_ Unimplemented) RotateAdminSmsCredentials(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List admin users
// (GET /v3/admin/users)
func (_ Unimplemented) GetAdminUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an admin user
// (POST /v3/admin/users)
func (_ Unimplemented) CreateAdminUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send an Email
// (POST /v3/email)
func (_ Unimplemented) PostV3Email(w http.ResponseWriter, r *http.Request, params PostV3EmailParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send an SMS
// (POST /v3/sms)
func (_ Unimplemented) PostV3Sms(w http.ResponseWriter, r *http.Request, params PostV3SmsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminLogin operation middleware
func (siw *ServerInterfaceWrapper) AdminLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAdminAuthMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetV3AdminDashboard operation middleware
func (siw *ServerInterfaceWrapper) GetV3AdminDashboard(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV3AdminDashboard(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminEmailAccounts operation middleware
func (siw *ServerInterfaceWrapper) GetAdminEmailAccounts(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminEmailAccounts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAdminEmailAccount operation middleware
func (siw *ServerInterfaceWrapper) CreateAdminEmailAccount(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAdminEmailAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAdminEmailAccount operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdminEmailAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId string

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", chi.URLParam(r, "accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAdminEmailAccount(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminEmailAccount operation middleware
func (siw *ServerInterfaceWrapper) GetAdminEmailAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId string

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", chi.URLParam(r, "accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminEmailAccount(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAdminEmailAccount operation middleware
func (siw *ServerInterfaceWrapper) UpdateAdminEmailAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId string

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", chi.URLParam(r, "accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAdminEmailAccount(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TestAdminEmailAccount operation middleware
func (siw *ServerInterfaceWrapper) TestAdminEmailAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId string

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", chi.URLParam(r, "accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestAdminEmailAccount(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminMessages operation middleware
func (siw *ServerInterfaceWrapper) GetAdminMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAdminMessagesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "channel" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "channel", r.URL.Query(), &params.Channel, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "channel"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channel", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "serviceId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "serviceId", r.URL.Query(), &params.ServiceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "serviceId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminMessages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAdminMessage operation middleware
func (siw *ServerInterfaceWrapper) CreateAdminMessage(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAdminMessage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PreviewAdminMessage operation middleware
func (siw *ServerInterfaceWrapper) PreviewAdminMessage(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PreviewAdminMessage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminServices operation middleware
func (siw *ServerInterfaceWrapper) GetAdminServices(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminServices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAdminService operation middleware
func (siw *ServerInterfaceWrapper) CreateAdminService(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAdminService(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAdminService operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdminService(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "serviceId" -------------
	var serviceId string

	err = runtime.BindStyledParameterWithOptions("simple", "serviceId", chi.URLParam(r, "serviceId"), &serviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAdminService(w, r, serviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminService operation middleware
func (siw *ServerInterfaceWrapper) GetAdminService(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "serviceId" -------------
	var serviceId string

	err = runtime.BindStyledParameterWithOptions("simple", "serviceId", chi.URLParam(r, "serviceId"), &serviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminService(w, r, serviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAdminService operation middleware
func (siw *ServerInterfaceWrapper) UpdateAdminService(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "serviceId" -------------
	var serviceId string

	err = runtime.BindStyledParameterWithOptions("simple", "serviceId", chi.URLParam(r, "serviceId"), &serviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAdminService(w, r, serviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RerollAdminService operation middleware
func (siw *ServerInterfaceWrapper) RerollAdminService(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "serviceId" -------------
	var serviceId string

	err = runtime.BindStyledParameterWithOptions("simple", "serviceId", chi.URLParam(r, "serviceId"), &serviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RerollAdminService(w, r, serviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminSmsCredentials operation middleware
func (siw *ServerInterfaceWrapper) GetAdminSmsCredentials(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminSmsCredentials(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAdminSmsCredentials operation middleware
func (siw *ServerInterfaceWrapper) UpdateAdminSmsCredentials(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAdminSmsCredentials(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RotateAdminSmsCredentials operation middleware
func (siw *ServerInterfaceWrapper) RotateAdminSmsCredentials(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RotateAdminSmsCredentials(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminUsers operation middleware
func (siw *ServerInterfaceWrapper) GetAdminUsers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAdminUser operation middleware
func (siw *ServerInterfaceWrapper) CreateAdminUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AdminBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAdminUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostV3Email operation middleware
func (siw *ServerInterfaceWrapper) PostV3Email(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, SignatureAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params PostV3EmailParams

	headers := r.Header

	// ------------- Required header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId ClientIdHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Client-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Client-Id", Err: err})
			return
		}

		params.XClientId = XClientId

	} else {
		err := fmt.Errorf("Header parameter X-Client-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Client-Id", Err: err})
		return
	}

	// ------------- Required header parameter "X-Timestamp" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Timestamp")]; found {
		var XTimestamp TimestampHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Timestamp", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Timestamp", valueList[0], &XTimestamp, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "date-time"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Timestamp", Err: err})
			return
		}

		params.XTimestamp = XTimestamp

	} else {
		err := fmt.Errorf("Header parameter X-Timestamp is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Timestamp", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV3Email(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostV3Sms operation middleware
func (siw *ServerInterfaceWrapper) PostV3Sms(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, SignatureAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params PostV3SmsParams

	headers := r.Header

	// ------------- Required header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId ClientIdHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Client-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Client-Id", Err: err})
			return
		}

		params.XClientId = XClientId

	} else {
		err := fmt.Errorf("Header parameter X-Client-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Client-Id", Err: err})
		return
	}

	// ------------- Required header parameter "X-Timestamp" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Timestamp")]; found {
		var XTimestamp TimestampHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Timestamp", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Timestamp", valueList[0], &XTimestamp, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "date-time"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Timestamp", Err: err})
			return
		}

		params.XTimestamp = XTimestamp

	} else {
		err := fmt.Errorf("Header parameter X-Timestamp is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Timestamp", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV3Sms(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v3/admin/auth/login", wrapper.AdminLogin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v3/admin/auth/me", wrapper.GetAdminAuthMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v3/admin/dashboard", wrapper.GetV3AdminDashboard)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v3/admin/email-accounts", wrapper.GetAdminEmailAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v3/admin/email-accounts", wrapper.CreateAdminEmailAccount)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v3/admin/email-accounts/{accountId}", wrapper.DeleteAdminEmailAccount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v3/admin/email-accounts/{accountId}", wrapper.GetAdminEmailAccount)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/v3/admin/email-accounts/{accountId}", wrapper.UpdateAdminEmailAccount)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v3/admin/email-accounts/{accountId}/test", wrapper.TestAdminEmailAccount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v3/admin/messages", wrapper.GetAdminMessages)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v3/admin/messages", wrapper.CreateAdminMessage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v3/admin/messages/preview", wrapper.PreviewAdminMessage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v3/admin/services", wrapper.GetAdminServices)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v3/admin/services", wrapper.CreateAdminService)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v3/admin/services/{serviceId}", wrapper.DeleteAdminService)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v3/admin/services/{serviceId}", wrapper.GetAdminService)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/v3/admin/services/{serviceId}", wrapper.UpdateAdminService)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v3/admin/services/{serviceId}/reroll", wrapper.RerollAdminService)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v3/admin/sms-credentials", wrapper.GetAdminSmsCredentials)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/v3/admin/sms-credentials", wrapper.UpdateAdminSmsCredentials)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v3/admin/sms-credentials/rotate", wrapper.RotateAdminSmsCredentials)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v3/admin/users", wrapper.GetAdminUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v3/admin/users", wrapper.CreateAdminUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v3/email", wrapper.PostV3Email)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v3/sms", wrapper.PostV3Sms)
	})

	return r
}
