// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package db

import (
	"context"
	"time"
)

const insertActivity = `-- name: InsertActivity :exec
INSERT INTO activity_log (id, title, detail, tone, entity_type, entity_id, metadata_json, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertActivityParams struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	Detail       string    `json:"detail"`
	Tone         string    `json:"tone"`
	EntityType   *string   `json:"entity_type"`
	EntityID     *string   `json:"entity_id"`
	MetadataJson *string   `json:"metadata_json"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.ExecContext(ctx, insertActivity,
		arg.ID,
		arg.Title,
		arg.Detail,
		arg.Tone,
		arg.EntityType,
		arg.EntityID,
		arg.MetadataJson,
		arg.CreatedAt,
	)
	return err
}

const listActivities = `-- name: ListActivities :many
SELECT id, title, detail, tone, entity_type, entity_id, metadata_json, created_at
FROM activity_log
ORDER BY created_at DESC, id DESC
LIMIT ?
`

func (q *Queries) ListActivities(ctx context.Context, limit int64) ([]ActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, listActivities, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Detail,
			&i.Tone,
			&i.EntityType,
			&i.EntityID,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
