// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_users.sql

package db

import (
	"context"
	"time"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT COUNT(*) AS count
FROM admin_users
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminSession = `-- name: CreateAdminSession :one
INSERT INTO admin_sessions (token_hash, user_id, created_at, expires_at, last_used_at, revoked_at, user_agent, remote_addr)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING token_hash, user_id, created_at, expires_at, last_used_at, revoked_at, user_agent, remote_addr
`

type CreateAdminSessionParams struct {
	TokenHash  string     `json:"token_hash"`
	UserID     string     `json:"user_id"`
	CreatedAt  time.Time  `json:"created_at"`
	ExpiresAt  time.Time  `json:"expires_at"`
	LastUsedAt time.Time  `json:"last_used_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
	UserAgent  *string    `json:"user_agent"`
	RemoteAddr *string    `json:"remote_addr"`
}

func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (AdminSession, error) {
	row := q.db.QueryRowContext(ctx, createAdminSession,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
		arg.RevokedAt,
		arg.UserAgent,
		arg.RemoteAddr,
	)
	var i AdminSession
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.RemoteAddr,
	)
	return i, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (id, username, password_hash, totp_secret, created_at, updated_at, last_login_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, username, created_at, updated_at, last_login_at
`

type CreateAdminUserParams struct {
	ID           string     `json:"id"`
	Username     string     `json:"username"`
	PasswordHash string     `json:"password_hash"`
	TotpSecret   string     `json:"totp_secret"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	LastLoginAt  *time.Time `json:"last_login_at"`
}

type CreateAdminUserRow struct {
	ID          string     `json:"id"`
	Username    string     `json:"username"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	LastLoginAt *time.Time `json:"last_login_at"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (CreateAdminUserRow, error) {
	row := q.db.QueryRowContext(ctx, createAdminUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.TotpSecret,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastLoginAt,
	)
	var i CreateAdminUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getAdminSessionByTokenHash = `-- name: GetAdminSessionByTokenHash :one
SELECT token_hash, user_id, created_at, expires_at, last_used_at, revoked_at, user_agent, remote_addr
FROM admin_sessions
WHERE token_hash = ?
`

func (q *Queries) GetAdminSessionByTokenHash(ctx context.Context, tokenHash string) (AdminSession, error) {
	row := q.db.QueryRowContext(ctx, getAdminSessionByTokenHash, tokenHash)
	var i AdminSession
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.RemoteAddr,
	)
	return i, err
}

const getAdminUserByUsername = `-- name: GetAdminUserByUsername :one
SELECT id, username, password_hash, totp_secret, created_at, updated_at, last_login_at
FROM admin_users
WHERE username = ?
`

func (q *Queries) GetAdminUserByUsername(ctx context.Context, username string) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, getAdminUserByUsername, username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getAdminUserPublicByID = `-- name: GetAdminUserPublicByID :one
SELECT id, username, created_at, updated_at, last_login_at
FROM admin_users
WHERE id = ?
`

type GetAdminUserPublicByIDRow struct {
	ID          string     `json:"id"`
	Username    string     `json:"username"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	LastLoginAt *time.Time `json:"last_login_at"`
}

func (q *Queries) GetAdminUserPublicByID(ctx context.Context, id string) (GetAdminUserPublicByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminUserPublicByID, id)
	var i GetAdminUserPublicByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT id, username, created_at, updated_at, last_login_at
FROM admin_users
ORDER BY created_at ASC, username ASC
`

type ListAdminUsersRow struct {
	ID          string     `json:"id"`
	Username    string     `json:"username"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	LastLoginAt *time.Time `json:"last_login_at"`
}

func (q *Queries) ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminUsersRow
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAdminSession = `-- name: TouchAdminSession :exec
UPDATE admin_sessions
SET last_used_at = ?
WHERE token_hash = ?
`

type TouchAdminSessionParams struct {
	LastUsedAt time.Time `json:"last_used_at"`
	TokenHash  string    `json:"token_hash"`
}

func (q *Queries) TouchAdminSession(ctx context.Context, arg TouchAdminSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchAdminSession, arg.LastUsedAt, arg.TokenHash)
	return err
}

const updateAdminUserLastLogin = `-- name: UpdateAdminUserLastLogin :exec
UPDATE admin_users
SET last_login_at = ?
WHERE id = ?
`

type UpdateAdminUserLastLoginParams struct {
	LastLoginAt *time.Time `json:"last_login_at"`
	ID          string     `json:"id"`
}

func (q *Queries) UpdateAdminUserLastLogin(ctx context.Context, arg UpdateAdminUserLastLoginParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminUserLastLogin, arg.LastLoginAt, arg.ID)
	return err
}
