// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_accounts.sql

package db

import (
	"context"
	"time"
)

const deleteAllEmailAccounts = `-- name: DeleteAllEmailAccounts :exec
DELETE FROM email_accounts
`

func (q *Queries) DeleteAllEmailAccounts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllEmailAccounts)
	return err
}

const insertEmailAccount = `-- name: InsertEmailAccount :exec
INSERT INTO email_accounts (id, address, display_name, smtp_host, smtp_port, smtp_username, smtp_password, is_default, status, last_tested_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEmailAccountParams struct {
	ID           string     `json:"id"`
	Address      string     `json:"address"`
	DisplayName  string     `json:"display_name"`
	SmtpHost     string     `json:"smtp_host"`
	SmtpPort     int64      `json:"smtp_port"`
	SmtpUsername string     `json:"smtp_username"`
	SmtpPassword string     `json:"smtp_password"`
	IsDefault    bool       `json:"is_default"`
	Status       string     `json:"status"`
	LastTestedAt *time.Time `json:"last_tested_at"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

func (q *Queries) InsertEmailAccount(ctx context.Context, arg InsertEmailAccountParams) error {
	_, err := q.db.ExecContext(ctx, insertEmailAccount,
		arg.ID,
		arg.Address,
		arg.DisplayName,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SmtpUsername,
		arg.SmtpPassword,
		arg.IsDefault,
		arg.Status,
		arg.LastTestedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listEmailAccounts = `-- name: ListEmailAccounts :many
SELECT id, address, display_name, smtp_host, smtp_port, smtp_username, smtp_password, is_default, status, last_tested_at, created_at, updated_at
FROM email_accounts
ORDER BY is_default DESC, created_at DESC, id ASC
`

func (q *Queries) ListEmailAccounts(ctx context.Context) ([]EmailAccount, error) {
	rows, err := q.db.QueryContext(ctx, listEmailAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailAccount
	for rows.Next() {
		var i EmailAccount
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.DisplayName,
			&i.SmtpHost,
			&i.SmtpPort,
			&i.SmtpUsername,
			&i.SmtpPassword,
			&i.IsDefault,
			&i.Status,
			&i.LastTestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
