// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"time"
)

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (id, channel, service_id, sender, subject, content_mode, body, template_name, request_json, rendered_text, status, created_at, queued_at, accepted_at, provider_message_id, provider_response_json, error_code, error_message, cost, currency)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMessageParams struct {
	ID                   string     `json:"id"`
	Channel              string     `json:"channel"`
	ServiceID            string     `json:"service_id"`
	Sender               string     `json:"sender"`
	Subject              *string    `json:"subject"`
	ContentMode          string     `json:"content_mode"`
	Body                 *string    `json:"body"`
	TemplateName         *string    `json:"template_name"`
	RequestJson          string     `json:"request_json"`
	RenderedText         string     `json:"rendered_text"`
	Status               string     `json:"status"`
	CreatedAt            time.Time  `json:"created_at"`
	QueuedAt             time.Time  `json:"queued_at"`
	AcceptedAt           *time.Time `json:"accepted_at"`
	ProviderMessageID    *string    `json:"provider_message_id"`
	ProviderResponseJson *string    `json:"provider_response_json"`
	ErrorCode            *string    `json:"error_code"`
	ErrorMessage         *string    `json:"error_message"`
	Cost                 *float64   `json:"cost"`
	Currency             *string    `json:"currency"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.ID,
		arg.Channel,
		arg.ServiceID,
		arg.Sender,
		arg.Subject,
		arg.ContentMode,
		arg.Body,
		arg.TemplateName,
		arg.RequestJson,
		arg.RenderedText,
		arg.Status,
		arg.CreatedAt,
		arg.QueuedAt,
		arg.AcceptedAt,
		arg.ProviderMessageID,
		arg.ProviderResponseJson,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Cost,
		arg.Currency,
	)
	return err
}

const insertMessageRecipient = `-- name: InsertMessageRecipient :exec
INSERT INTO message_recipients (message_id, ordinal, recipient, recipient_name, country_code)
VALUES (?, ?, ?, ?, ?)
`

type InsertMessageRecipientParams struct {
	MessageID     string  `json:"message_id"`
	Ordinal       int64   `json:"ordinal"`
	Recipient     string  `json:"recipient"`
	RecipientName *string `json:"recipient_name"`
	CountryCode   *string `json:"country_code"`
}

func (q *Queries) InsertMessageRecipient(ctx context.Context, arg InsertMessageRecipientParams) error {
	_, err := q.db.ExecContext(ctx, insertMessageRecipient,
		arg.MessageID,
		arg.Ordinal,
		arg.Recipient,
		arg.RecipientName,
		arg.CountryCode,
	)
	return err
}

const listMessageRecipientsByMessageID = `-- name: ListMessageRecipientsByMessageID :many
SELECT id, message_id, ordinal, recipient, recipient_name, country_code
FROM message_recipients
WHERE message_id = ?
ORDER BY ordinal ASC
`

func (q *Queries) ListMessageRecipientsByMessageID(ctx context.Context, messageID string) ([]MessageRecipient, error) {
	rows, err := q.db.QueryContext(ctx, listMessageRecipientsByMessageID, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageRecipient
	for rows.Next() {
		var i MessageRecipient
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Ordinal,
			&i.Recipient,
			&i.RecipientName,
			&i.CountryCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, channel, service_id, sender, subject, content_mode, body, template_name, request_json, rendered_text, status, created_at, queued_at, accepted_at, provider_message_id, provider_response_json, error_code, error_message, cost, currency
FROM messages
ORDER BY created_at DESC, id DESC
LIMIT ?
`

func (q *Queries) ListMessages(ctx context.Context, limit int64) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.ServiceID,
			&i.Sender,
			&i.Subject,
			&i.ContentMode,
			&i.Body,
			&i.TemplateName,
			&i.RequestJson,
			&i.RenderedText,
			&i.Status,
			&i.CreatedAt,
			&i.QueuedAt,
			&i.AcceptedAt,
			&i.ProviderMessageID,
			&i.ProviderResponseJson,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Cost,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
