// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type ActivityLog struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	Detail       string    `json:"detail"`
	Tone         string    `json:"tone"`
	EntityType   *string   `json:"entity_type"`
	EntityID     *string   `json:"entity_id"`
	MetadataJson *string   `json:"metadata_json"`
	CreatedAt    time.Time `json:"created_at"`
}

type AdminSession struct {
	TokenHash  string     `json:"token_hash"`
	UserID     string     `json:"user_id"`
	CreatedAt  time.Time  `json:"created_at"`
	ExpiresAt  time.Time  `json:"expires_at"`
	LastUsedAt time.Time  `json:"last_used_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
	UserAgent  *string    `json:"user_agent"`
	RemoteAddr *string    `json:"remote_addr"`
}

type AdminUser struct {
	ID           string     `json:"id"`
	Username     string     `json:"username"`
	PasswordHash string     `json:"password_hash"`
	TotpSecret   string     `json:"totp_secret"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	LastLoginAt  *time.Time `json:"last_login_at"`
}

type AppSetting struct {
	ID               int64     `json:"id"`
	ServerHost       string    `json:"server_host"`
	ServerPort       int64     `json:"server_port"`
	Debug            bool      `json:"debug"`
	AdminBearerToken string    `json:"admin_bearer_token"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type EmailAccount struct {
	ID           string     `json:"id"`
	Address      string     `json:"address"`
	DisplayName  string     `json:"display_name"`
	SmtpHost     string     `json:"smtp_host"`
	SmtpPort     int64      `json:"smtp_port"`
	SmtpUsername string     `json:"smtp_username"`
	SmtpPassword string     `json:"smtp_password"`
	IsDefault    bool       `json:"is_default"`
	Status       string     `json:"status"`
	LastTestedAt *time.Time `json:"last_tested_at"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

type Message struct {
	ID                   string     `json:"id"`
	Channel              string     `json:"channel"`
	ServiceID            string     `json:"service_id"`
	Sender               string     `json:"sender"`
	Subject              *string    `json:"subject"`
	ContentMode          string     `json:"content_mode"`
	Body                 *string    `json:"body"`
	TemplateName         *string    `json:"template_name"`
	RequestJson          string     `json:"request_json"`
	RenderedText         string     `json:"rendered_text"`
	Status               string     `json:"status"`
	CreatedAt            time.Time  `json:"created_at"`
	QueuedAt             time.Time  `json:"queued_at"`
	AcceptedAt           *time.Time `json:"accepted_at"`
	ProviderMessageID    *string    `json:"provider_message_id"`
	ProviderResponseJson *string    `json:"provider_response_json"`
	ErrorCode            *string    `json:"error_code"`
	ErrorMessage         *string    `json:"error_message"`
	Cost                 *float64   `json:"cost"`
	Currency             *string    `json:"currency"`
}

type MessageRecipient struct {
	ID            int64   `json:"id"`
	MessageID     string  `json:"message_id"`
	Ordinal       int64   `json:"ordinal"`
	Recipient     string  `json:"recipient"`
	RecipientName *string `json:"recipient_name"`
	CountryCode   *string `json:"country_code"`
}

type Service struct {
	ID              string     `json:"id"`
	Name            string     `json:"name"`
	Owner           string     `json:"owner"`
	Scope           string     `json:"scope"`
	Status          string     `json:"status"`
	PublicKey       string     `json:"public_key"`
	Notes           string     `json:"notes"`
	CreatedAt       time.Time  `json:"created_at"`
	LastRerollAt    *time.Time `json:"last_reroll_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	EmailAccessMode string     `json:"email_access_mode"`
}

type ServiceEmailAccount struct {
	ServiceID      string    `json:"service_id"`
	EmailAccountID string    `json:"email_account_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type SmsCredential struct {
	ID            int64     `json:"id"`
	Username      string    `json:"username"`
	Password      string    `json:"password"`
	Status        string    `json:"status"`
	LastSyncedAt  time.Time `json:"last_synced_at"`
	RotationCount int64     `json:"rotation_count"`
	UpdatedAt     time.Time `json:"updated_at"`
}
