// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package db

import (
	"context"
	"time"
)

const deleteAllServices = `-- name: DeleteAllServices :exec
DELETE FROM services
`

func (q *Queries) DeleteAllServices(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllServices)
	return err
}

const insertService = `-- name: InsertService :exec
INSERT INTO services (id, name, owner, scope, email_access_mode, status, public_key, notes, created_at, last_reroll_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertServiceParams struct {
	ID              string     `json:"id"`
	Name            string     `json:"name"`
	Owner           string     `json:"owner"`
	Scope           string     `json:"scope"`
	EmailAccessMode string     `json:"email_access_mode"`
	Status          string     `json:"status"`
	PublicKey       string     `json:"public_key"`
	Notes           string     `json:"notes"`
	CreatedAt       time.Time  `json:"created_at"`
	LastRerollAt    *time.Time `json:"last_reroll_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) InsertService(ctx context.Context, arg InsertServiceParams) error {
	_, err := q.db.ExecContext(ctx, insertService,
		arg.ID,
		arg.Name,
		arg.Owner,
		arg.Scope,
		arg.EmailAccessMode,
		arg.Status,
		arg.PublicKey,
		arg.Notes,
		arg.CreatedAt,
		arg.LastRerollAt,
		arg.UpdatedAt,
	)
	return err
}

const listServices = `-- name: ListServices :many
SELECT id, name, owner, scope, email_access_mode, status, public_key, notes, created_at, last_reroll_at, updated_at
FROM services
ORDER BY created_at DESC, id ASC
`

type ListServicesRow struct {
	ID              string     `json:"id"`
	Name            string     `json:"name"`
	Owner           string     `json:"owner"`
	Scope           string     `json:"scope"`
	EmailAccessMode string     `json:"email_access_mode"`
	Status          string     `json:"status"`
	PublicKey       string     `json:"public_key"`
	Notes           string     `json:"notes"`
	CreatedAt       time.Time  `json:"created_at"`
	LastRerollAt    *time.Time `json:"last_reroll_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) ListServices(ctx context.Context) ([]ListServicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServicesRow
	for rows.Next() {
		var i ListServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Owner,
			&i.Scope,
			&i.EmailAccessMode,
			&i.Status,
			&i.PublicKey,
			&i.Notes,
			&i.CreatedAt,
			&i.LastRerollAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
