// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_email_accounts.sql

package db

import (
	"context"
	"time"
)

const deleteAllServiceEmailAccounts = `-- name: DeleteAllServiceEmailAccounts :exec
DELETE FROM service_email_accounts
`

func (q *Queries) DeleteAllServiceEmailAccounts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllServiceEmailAccounts)
	return err
}

const insertServiceEmailAccount = `-- name: InsertServiceEmailAccount :exec
INSERT INTO service_email_accounts (service_id, email_account_id, created_at)
VALUES (?, ?, ?)
`

type InsertServiceEmailAccountParams struct {
	ServiceID      string    `json:"service_id"`
	EmailAccountID string    `json:"email_account_id"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) InsertServiceEmailAccount(ctx context.Context, arg InsertServiceEmailAccountParams) error {
	_, err := q.db.ExecContext(ctx, insertServiceEmailAccount, arg.ServiceID, arg.EmailAccountID, arg.CreatedAt)
	return err
}

const listServiceEmailAccounts = `-- name: ListServiceEmailAccounts :many
SELECT service_id, email_account_id, created_at
FROM service_email_accounts
ORDER BY service_id ASC, email_account_id ASC
`

func (q *Queries) ListServiceEmailAccounts(ctx context.Context) ([]ServiceEmailAccount, error) {
	rows, err := q.db.QueryContext(ctx, listServiceEmailAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceEmailAccount
	for rows.Next() {
		var i ServiceEmailAccount
		if err := rows.Scan(&i.ServiceID, &i.EmailAccountID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
