// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package db

import (
	"context"
	"time"
)

const getAppSettings = `-- name: GetAppSettings :one
SELECT id, server_host, server_port, debug, admin_bearer_token, updated_at
FROM app_settings
WHERE id = 1
`

func (q *Queries) GetAppSettings(ctx context.Context) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, getAppSettings)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.ServerHost,
		&i.ServerPort,
		&i.Debug,
		&i.AdminBearerToken,
		&i.UpdatedAt,
	)
	return i, err
}

const getSmsCredentials = `-- name: GetSmsCredentials :one
SELECT id, username, password, status, last_synced_at, rotation_count, updated_at
FROM sms_credentials
WHERE id = 1
`

func (q *Queries) GetSmsCredentials(ctx context.Context) (SmsCredential, error) {
	row := q.db.QueryRowContext(ctx, getSmsCredentials)
	var i SmsCredential
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Status,
		&i.LastSyncedAt,
		&i.RotationCount,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAppSettings = `-- name: UpsertAppSettings :exec
INSERT INTO app_settings (id, server_host, server_port, debug, admin_bearer_token, updated_at)
VALUES (1, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  server_host = excluded.server_host,
  server_port = excluded.server_port,
  debug = excluded.debug,
  admin_bearer_token = excluded.admin_bearer_token,
  updated_at = excluded.updated_at
`

type UpsertAppSettingsParams struct {
	ServerHost       string    `json:"server_host"`
	ServerPort       int64     `json:"server_port"`
	Debug            bool      `json:"debug"`
	AdminBearerToken string    `json:"admin_bearer_token"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) UpsertAppSettings(ctx context.Context, arg UpsertAppSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertAppSettings,
		arg.ServerHost,
		arg.ServerPort,
		arg.Debug,
		arg.AdminBearerToken,
		arg.UpdatedAt,
	)
	return err
}

const upsertSmsCredentials = `-- name: UpsertSmsCredentials :exec
INSERT INTO sms_credentials (id, username, password, status, last_synced_at, rotation_count, updated_at)
VALUES (1, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  username = excluded.username,
  password = excluded.password,
  status = excluded.status,
  last_synced_at = excluded.last_synced_at,
  rotation_count = excluded.rotation_count,
  updated_at = excluded.updated_at
`

type UpsertSmsCredentialsParams struct {
	Username      string    `json:"username"`
	Password      string    `json:"password"`
	Status        string    `json:"status"`
	LastSyncedAt  time.Time `json:"last_synced_at"`
	RotationCount int64     `json:"rotation_count"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) UpsertSmsCredentials(ctx context.Context, arg UpsertSmsCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, upsertSmsCredentials,
		arg.Username,
		arg.Password,
		arg.Status,
		arg.LastSyncedAt,
		arg.RotationCount,
		arg.UpdatedAt,
	)
	return err
}
